name:                dilemma
version:             0.1.0.0
github:              "Acaccia/dilemma"
license:             BSD3
author:              "Anthony Caccia"
maintainer:          "acaccia@ulb.ac.be"
copyright:           "ACaccia"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Acaccia/dilemma#readme>

dependencies:
- base >= 4.7 && < 5
- repa

library:
  source-dirs: src

executables:
  dilemma-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dilemma

tests:
  dilemma-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dilemma
